version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - royal-madness-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    restart: unless-stopped

volumes:
  royal-madness-data:
    name: royal-madness-data