packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^5.2.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@d-fischer/typed-event-emitter': ^3.3.3
  '@donation-alerts/api': ^4.0.0
  '@donation-alerts/auth': ^4.0.0
  '@donation-alerts/events': ^4.0.0
  '@iconify-json/lucide': ^1.2.65
  '@iconify-json/simple-icons': ^1.2.49
  '@iconify/vue': ^5.0.0
  '@neoconfetti/vue': ^2.2.1
  '@number-flow/vue': ^0.4.8
  '@nuxt/devtools': ^2.6.3
  '@nuxt/ui': ^3.3.2
  '@nuxtjs/i18n': ^10.0.6
  '@paralleldrive/cuid2': ^2.2.2
  '@prisma/client': ^6.15.0
  '@tailwindcss/vite': ^4.1.12
  '@telegram-apps/init-data-node': ^1.2.2
  '@telegram-apps/sdk-vue': ^1.0.15
  '@tsconfig/node22': ^22.0.2
  '@tsparticles/engine': ^3.9.1
  '@tsparticles/slim': ^3.9.1
  '@tsparticles/vue3': ^3.0.1
  '@twurple/api': ^7.4.0
  '@twurple/auth': ^7.4.0
  '@twurple/chat': ^7.4.0
  '@twurple/easy-bot': ^7.4.0
  '@twurple/eventsub-ws': ^7.4.0
  '@types/howler': ^2.2.12
  '@types/node': ^24.3.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vue/tsconfig': ^0.8.1
  '@vueuse/components': ^13.8.0
  '@vueuse/core': ^13.8.0
  '@vueuse/nuxt': ^13.8.0
  changelogen-monorepo: ^0.5.0
  eruda: ^3.4.3
  eslint: ^9.34.0
  grammy: ^1.38.1
  howler: ^2.2.4
  husky: ^9.1.7
  ioredis: ^5.7.0
  lint-staged: ^16.1.5
  nuxt: ^4.0.3
  nuxt-auth-utils: ^0.5.23
  pixi.js: ^8.12.0
  playwright: ^1.55.0
  prisma: ^6.15.0
  tailwindcss: ^4.1.12
  typescript: ^5.9.2
  unplugin-auto-import: ^20.1.0
  unplugin-icons: ^22.2.0
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.3
  vite-plugin-terminal: ^1.3.0
  vite-plugin-vue-devtools: ^8.0.1
  vitest: ^3.2.4
  vitest-browser-vue: ^1.1.0
  vue: ^3.5.20
  vue-i18n: ^11.1.11
  vue-router: ^4.5.1
  vue-tsc: ^3.0.6
  zod: ^4.1.5
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
onlyBuiltDependencies:
  - sharp
  - protobufjs
supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]
