packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@d-fischer/typed-event-emitter': ^3.3.3
  '@donation-alerts/api': ^4.0.0
  '@donation-alerts/auth': ^4.0.0
  '@donation-alerts/events': ^4.0.0
  '@iconify-json/lucide': ^1.2.39
  '@iconify-json/simple-icons': ^1.2.33
  '@iconify/vue': ^5.0.0
  '@neoconfetti/vue': ^2.2.1
  '@number-flow/vue': ^0.4.7
  '@nuxt/devtools': ^2.4.0
  '@nuxt/fonts': ^0.11.2
  '@nuxt/icon': ^1.12.0
  '@nuxt/kit': ^3.17.1
  '@nuxtjs/i18n': ^9.5.4
  '@paralleldrive/cuid2': ^2.2.2
  '@prisma/client': ^6.2.1
  '@tailwindcss/vite': ^4.1.5
  '@telegram-apps/init-data-node': ^1.2.2
  '@telegram-apps/sdk-vue': ^1.0.15
  '@tsconfig/node22': ^22.0.1
  '@tsparticles/engine': ^3.8.1
  '@tsparticles/slim': ^3.8.1
  '@tsparticles/vue3': ^3.0.1
  '@twurple/api': ^7.3.0
  '@twurple/auth': ^7.3.0
  '@twurple/chat': ^7.3.0
  '@twurple/easy-bot': ^7.3.0
  '@twurple/eventsub-ws': ^7.3.0
  '@types/howler': ^2.2.12
  '@types/node': ^22.15.3
  '@vitejs/plugin-vue': ^5.2.3
  '@vitest/browser': ^3.1.2
  '@vitest/coverage-v8': ^3.1.2
  '@vue/tsconfig': ^0.7.0
  '@vueuse/components': ^13.1.0
  '@vueuse/core': ^13.1.0
  '@vueuse/nuxt': ^13.1.0
  changelogen-monorepo: ^0.4.2
  dotenv-cli: ^8.0.0
  eruda: ^3.4.1
  grammy: ^1.36.1
  howler: ^2.2.4
  husky: ^9.1.7
  ioredis: ^5.6.1
  lint-staged: ^15.5.1
  nuxt: ^3.17.1
  nuxt-auth-utils: ^0.5.20
  pixi.js: ^8.9.2
  playwright: ^1.52.0
  prisma: ^6.2.1
  tailwindcss: ^4.0.4
  typescript: ^5.8.3
  unplugin-auto-import: ^19.1.2
  unplugin-icons: ^22.1.0
  unplugin-vue-components: ^28.5.0
  vite: ^6.3.4
  vite-plugin-terminal: ^1.3.0
  vite-plugin-vue-devtools: ^7.7.6
  vitest: ^3.1.2
  vitest-browser-vue: ^0.2.0
  vue: ^3.5.13
  vue-i18n: ^11.1.3
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
  zod: ^3.24.3
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
onlyBuiltDependencies:
  - sharp
  - protobufjs
supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]
