apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login-secret
  namespace: chat-game
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    To generate use command:
    kubectl create secret docker-registry ghcr-login-secret --namespace=chat-game --docker-email=$EMAIL --docker-username=$GITHUB_USERNAME --docker-server=https://ghcr.io --docker-password=$GITHUB_TOKEN
