version: '3.8'

services:
  chat-game-dev:
    build:
      context: ../
      dockerfile: .docker/Dockerfile.dev
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    volumes:
      - ..:/app
      - /app/node_modules
