/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveCard: typeof import('./src/components/ActiveCard.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CharacterActivationBlock: typeof import('./src/components/CharacterActivationBlock.vue')['default']
    CharacterAvatar: typeof import('./src/components/CharacterAvatar.vue')['default']
    CharacterCard: typeof import('./src/components/CharacterCard.vue')['default']
    CharacterProgressionModal: typeof import('./src/components/CharacterProgressionModal.vue')['default']
    CharacterUnlockBlock: typeof import('./src/components/CharacterUnlockBlock.vue')['default']
    ChristmasBackground: typeof import('./src/components/ChristmasBackground.vue')['default']
    CoinBackground: typeof import('./src/components/CoinBackground.vue')['default']
    ConfettiBackground: typeof import('./src/components/ConfettiBackground.vue')['default']
    CouponActivationBlock: typeof import('./src/components/CouponActivationBlock.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GameCharacterProgression: typeof import('./src/components/GameCharacterProgression.vue')['default']
    GameLoader: typeof import('./src/components/GameLoader.vue')['default']
    GameNavigator: typeof import('./src/components/GameNavigator.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    InventoryItemActivationBlock: typeof import('./src/components/InventoryItemActivationBlock.vue')['default']
    InventoryItemCard: typeof import('./src/components/InventoryItemCard.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    ProductActivationBlock: typeof import('./src/components/ProductActivationBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    WoodlandPointsBackground: typeof import('./src/components/WoodlandPointsBackground.vue')['default']
  }
}
