/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveCard: typeof import('./src/components/ActiveCard.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CharacterActivationBlock: typeof import('./src/components/CharacterActivationBlock.vue')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GameNavigator: typeof import('./src/components/GameNavigator.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
  }
}
