FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm i
COPY . .
RUN npm run build
RUN npm prune --production

FROM node:22-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 3000
CMD [ "node", "build" ]