name: Build and Push Docker Image

on:
  release:
    types:
      - created
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/app

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: VERSION=nightly
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:nightly

      - name: Build Docker (release)
        uses: docker/build-push-action@v5
        if: github.event_name == 'release'
        with:
          context: .
          build-args: VERSION=${{ github.event.release.name }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.release.name }},${{ env.IMAGE_NAME }}:latest
