name: Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: |
          npm i --legacy-peer-deps
          npm run lint
          npm run lint:deps
          npm run check
