name: Run Tests and Lint

on:
  push

permissions:
  contents: write

jobs:
  lint:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm ci --legacy-peer-deps

      - name: ESLint
        run: npm run lint

      - name: Find circular dependencies
        run: npm run lint:deps

      - name: Check Svelte files
        run: npm run check

      - name: Check tests
        run: npm run test

      - name: Check Build
        run: npm run build
