name: Run Tests and Lint

on:
  push:
    paths-ignore:
      - "docs/**"
      - ".md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: ESLint
        run: yarn run lint

      - name: Find circular dependencies
        run: yarn run lint:deps

      - name: Check Svelte files
        run: yarn run check

      - name: Check tests
        run: yarn run test

      - name: Check Build
        run: yarn run build
