name: Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - name: Lint
        run: |
          bun run lint
          bun run lint:deps
          bun run check
